[build]
  command = "ng build --configuration production"
  publish = "dist/dreamlab"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  ANGULAR_CONFIGURATION = "production"
